### PR TITLE
[service]: fix the previous button 

### LINKED ISSUE #382: First audio of a queue is played twice

### PR DESCRIPTION
**Pull request by soumyaDghosh**
The index of the next song was not updated, when we change the song. As a result, each song, that's played by pressing the previous button, will play again, if we press the next button. What this PR does is, sets audio index, to the previous song of the current audio. Then updates the index of the next song. Not sure about this, but I think we should not return if the next song is null.

fixes #382

### CODE REVIEW

File: lib/src/player/player_service.dart [hunk 1]
```diff
@@ -307,7 +307,7 @@ class PlayerService {
     nextAudio = queue.$2.elementAt(randomIndex);
   }
 
-  Future<void> playPrevious() async {
+  Future<void> playPrevious({bool doubleTap = false}) async {
```
Comment (Feichtmeier) [inline lib/src/player/player_service.dart:310]: what is this flag currently used for?

File: lib/src/player/player_service.dart [hunk 2]
```diff
@@ -316,11 +316,10 @@ class PlayerService {
...
         return;
       }
+      _setAudio(queue.$2.elementAt(currentIndex - 1));
+      nextAudio = queue.$2.elementAt(queue.$2.indexOf(audio!) + 1);
 
-      nextAudio = queue.$2.elementAt(currentIndex - 1);
-
-      if (nextAudio == null) return;
-      _setAudio(nextAudio);
+      // if (nextAudio == null) return;
```
Comment (Feichtmeier) [inline lib/src/player/player_service.dart:322]: remove this line if you dont use it

**Review by Feichtmeier — CHANGES_REQUESTED** [review]
Left two comments to resolve

File: lib/src/player/player_service.dart (hunk 1 above)
Comment (Feichtmeier) [reply lib/src/player/player_service.dart:310]: yeah no, just do one change after the othere, no need to place some lines in advance :)

File: lib/src/player/player_service.dart (hunk 2 above)
Comment (Feichtmeier) [reply lib/src/player/player_service.dart:322]: same as above, no need to place lines in advance with git

**Comment by soumyaDghosh** [comment]
Done!

**Review by Feichtmeier — APPROVED** [review]

**Review by Feichtmeier — APPROVED** [review]
